### PR TITLE
Review

### PR DESCRIPTION
**Pull request by pcuenca**

### CODE REVIEW

**Comment by dylanebert** [comment]
Thanks! I just now merged Omar's PR, can you rebase?

**Comment by pcuenca** [comment]
* I _think_ that links should not end with `.mdx`, but I might be wrong. Will try to run the doc-builder locally.
* The image in https://github.com/huggingface/ml-for-3d-course/edit/pcuenca-patch-1/units/en/unit1/pipelines.mdx is previewed as a large white square by GitHub (light mode).

**Comment by dylanebert** [comment]
> * I _think_ that links should not end with `.mdx`, but I might be wrong. Will try to run the doc-builder locally.
> * The image in https://github.com/huggingface/ml-for-3d-course/edit/pcuenca-patch-1/units/en/unit1/pipelines.mdx is previewed as a large white square by GitHub (light mode).

Thanks, will add a dark background on the image in documentation-images!

**Comment by pcuenca** [comment]
* In [Unit 2](https://github.com/huggingface/ml-for-3d-course/blob/pcuenca-patch-1/units/en/unit2/hands-on-1.mdx) they could use the repo duplicator space to get started: https://huggingface.co/spaces/huggingface-projects/repo_duplicator

**Pull request merged**
